version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretstuff
    volumes:
      - './schema.sql:/schema.sql'
      - mysql-data:/var/lib/mysql

  erstiwetool:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - './admin.htpasswd:/usr/src/app/admin.htpasswd'
      - './config.js:/usr/src/app/config.js'

volumes:
  mysql-data: